[build]
command = "npm run build"
functions = "functions"
publish = "_site"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--production=false"

[dev]
command = "npm run start"
functions = "functions"
publish = "_site"

[functions]
node_bundler = "esbuild"


[functions."chatrag"]
included_files = ["vector_store/docstore.json", "vector_store/faiss.index"]
external_node_modules = ["faiss-node"]
node_bundler = "nft"


[[redirects]]
from = "/notes/202507061346/*"
to = "/articles/creative-process-with-ai-on-ipad/:splat"
status = 301

[[redirects]]
from = "/notes/202507231344/*"
to = "/articles/wasted-25-years-writing-code-structured-communication/:splat"
status = 301

[[redirects]]
from = "/notes/202508102004/*"
to = "/articles/claude-code-instant-notifications-ntfy/:splat"
status = 301

[[redirects]]
from = "/.well-known/webfinger"
to = "https://mastodon.nz/.well-known/webfinger?resource=acct:andrewford@mastodon.nz"
status = 200
