[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild" 
  
[[plugins]]
package = "@resoc/netlify-plugin-social-image"

  [plugins.inputs]
  templates_dir = "resoc-templates"
  open_graph_base_path = "/social-images"
  slug_to_image_data_mapping_file = "resoc-image-data.json"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
