[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"

[dev]
  command = "npm run start"
  functions = "functions"
  publish = "_site"

[functions]
  node_bundler = "esbuild" 

[[plugins]]
package = "@resoc/netlify-plugin-social-image"

  [plugins.inputs]
  templates_dir = "resoc-templates"
  open_graph_base_path = "/social-images"
  slug_to_image_data_mapping_file = "resoc-image-data.json"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://mastodon.nz/.well-known/webfinger?resource=acct:andrewford@mastodon.nz"
  status = 200